export const themes = [
  { id: "light", name: "🌝  light" },
  { id: "dark", name: "🌚  dark" },
  { id: "cupcake", name: "🧁  cupcake" },
  { id: "bumblebee", name: "🐝  bumblebee" },
  { id: "emerald", name: "✳️  Emerald" },
  { id: "corporate", name: "🏢  Corporate" },
  { id: "synthwave", name: "🌃  synthwave" },
  { id: "retro", name: "👴  retro" },
  { id: "cyberpunk", name: "🤖  cyberpunk" },
  { id: "valentine", name: "🌸  valentine" },
  { id: "halloween", name: "🎃  halloween" },
  { id: "garden", name: "🌷  garden" },
  { id: "forest", name: "🌲  forest" },
  { id: "aqua", name: "🐟  aqua" },
  { id: "lofi", name: "👓  lofi" },
  { id: "pastel", name: "🖍  pastel" },
  { id: "fantasy", name: "🧚‍♀️  fantasy" },
  { id: "wireframe", name: "📝  Wireframe" },
  { id: "black", name: "🏴  black" },
  { id: "luxury", name: "💎  luxury" },
  { id: "dracula", name: "🧛‍♂️  dracula" },
];
